name: Compressed Size

on: [pull_request]

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: preactjs/compressed-size-action@2.6.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        pattern: "{build/**/*.js,build/**/*.css}"
